'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowDownLeft, ArrowUpRight, Check, Phone, PhoneOff, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { useReview } from './provider';
import { ActionLink, Badge, Card, Confirm, date, Editor, Empty, Heading, human, phoneHint, Stat, type Field } from './ui';

export function Overview() {
  const { state } = useReview();
  return <><Heading eyebrow="A little more breathing room" title={`Good to see you, ${state.profile.name.split(' ')[0]}.`} description="Your calls, considered. Here’s the shape of your day."><Button asChild><Link href="/demo/calls">Open your inbox <ArrowUpRight size={17} aria-hidden="true" /></Link></Button></Heading><div className="stat-grid"><Stat label="Calls in this sample" value={state.calls.length} detail="Illustrative activity" /><Stat label="Messages to read" value={state.calls.filter(call => call.unread && call.outcome === 'message').length} detail="A little context, ready for you" /><Stat label="Calls screened out" value={state.calls.filter(call => call.outcome === 'blocked').length} detail="Based on example outcomes" /><Stat label="Callbacks to make" value={state.callbacks.filter(callback => !callback.done).length} detail="Your personal follow-up list" /></div><div className="workspace-grid"><Card title="The calls that matter" subtitle="Recent example activity"><CallRows calls={state.calls.slice(0, 3)} /><ActionLink href="/demo/calls">View all calls</ActionLink></Card><Card className="violet-card" title="Your time. Your call." subtitle="Stay close to the conversation without giving up your day."><div className="orbit-art" aria-hidden="true"><div><Phone size={36} strokeWidth={1} /></div><span className="orbit-dot" /></div><p>Listen with Insider. Take over with Gavel. Guide with Audible. Connect with Directory.</p><Button asChild><Link href="/demo/live">Try the control simulator <ArrowUpRight size={17} aria-hidden="true" /></Link></Button></Card></div><div className="workspace-grid equal"><Card title="Make it yours"><div className="task-list"><ActionLink href="/demo/screening">Choose which calls to screen</ActionLink><ActionLink href="/demo/agent">Give your assistant a voice</ActionLink><ActionLink href="/demo/directory">Set up trusted destinations</ActionLink></div></Card><Card title="A clear next step"><p>A real number isn’t connected yet. Review the setup flow and select a connection path before testing a development voice service.</p><ActionLink href="/demo/onboarding">Continue setup</ActionLink><div className="mini-meter"><span style={{ width: `${state.setup.step * 25}%` }} /></div><p className="small-label">Local setup step {state.setup.step} of 4</p></Card></div></>;
}
function CallRows({ calls }: { calls: ReturnType<typeof useReview>['state']['calls'] }) {
  const { state } = useReview();
  return <ul className="review-call-list">{calls.map(call => <li key={call.id}><Link href={`/demo/calls/${call.id}`}><span className={`call-icon ${call.outcome === 'blocked' ? 'rose' : ''}`}>{call.outcome === 'blocked' ? <PhoneOff size={19} aria-hidden="true" /> : <ArrowDownLeft size={19} aria-hidden="true" />}</span><div className="call-copy"><strong>{call.caller}{call.unread && <span className="unread-dot" aria-label="Unread" />}</strong><p>{call.summary}</p><span className="small-label">{date(call.at, state.profile.timezone)} · {call.duration}s</span></div><Badge tone={call.outcome === 'blocked' ? 'rose' : call.outcome === 'connected' ? 'green' : ''}>{human(call.outcome)}</Badge><ArrowUpRight className="row-arrow" size={17} aria-hidden="true" /></Link></li>)}</ul>;
}
export function Calls() {
  const { state } = useReview(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all');
  const calls = state.calls.filter(call => (filter === 'all' || (filter === 'unread' ? call.unread : call.outcome === filter)) && `${call.caller} ${call.phone} ${call.summary}`.toLowerCase().includes(query.toLowerCase()));
  return <><Heading title="Room for a quieter day." description="Every conversation, with the context you need."><Button variant="outline" asChild><Link href="/demo/live">Open live simulator</Link></Button></Heading><div className="toolbar"><div className="search-field"><Search size={18} aria-hidden="true" /><Input aria-label="Search calls" placeholder="Search names, numbers or messages" value={query} onChange={event => setQuery(event.target.value)} /></div><label className="filter-label">Show<Select aria-label="Show" value={filter} onValueChange={setFilter} options={[{ value: "all", label: "All calls" }, { value: "unread", label: "Unread" }, { value: "message", label: "Messages" }, { value: "blocked", label: "Blocked" }, { value: "connected", label: "Connected" }, { value: "missed", label: "Missed" }]} /></label></div><Card><div className="list-heading"><h2>Your call inbox</h2><span className="small-label">{calls.length} example {calls.length === 1 ? 'call' : 'calls'}</span></div>{calls.length ? <CallRows calls={calls} /> : <Empty title="Nothing here just yet">Try another search or filter.</Empty>}</Card><div className="inline-note"><Check size={17} aria-hidden="true" /><p>Summaries make it easier to decide what deserves your attention. Every call in this review is fictional.</p></div></>;
}
export function CallDetail({ id }: { id: string }) {
  const { state, run, busy } = useReview(); const router = useRouter(); const call = state.calls.find(item => item.id === id); const [deleting, setDeleting] = useState(false);
  if (!call) return <><Heading title="Message unavailable" description="This example was removed or doesn’t exist." /><ActionLink href="/demo/calls">Return to the inbox</ActionLink></>;
  return <><ActionLink href="/demo/calls">Back to calls</ActionLink><Heading eyebrow={`${call.category} · Example call`} title={call.caller} description={`${call.phone} · ${date(call.at, state.profile.timezone)} · ${call.duration} seconds`}><Badge>{human(call.outcome)}</Badge><Button variant="outline" disabled={busy} onClick={() => run({ type: 'call.read', id, unread: !call.unread })}>{call.unread ? 'Mark as read' : 'Mark as unread'}</Button></Heading><div className="workspace-grid"><Card title="The conversation" subtitle="Illustrative transcript · no recording"><div className="transcript">{call.transcript.length ? call.transcript.map((line, index) => <div key={index} className={line.speaker === 'Caller' ? 'caller-line' : 'assistant-line'}><p className="speaker">{line.speaker}</p><p>{line.text}</p></div>) : <Empty title="No transcript">This call has no example transcript.</Empty>}</div></Card><div className="stack"><Card title="At a glance"><p>{call.summary}</p><div className="record-meta"><span>Outcome</span><strong>{human(call.outcome)}</strong><span>Recording</span><strong>Off</strong><span>Source</span><strong>Synthetic example</strong></div></Card><Card title="What’s next?"><p>Schedule a reminder, or update the outcome for your review.</p><CallbackEditor name={call.caller} phone={call.phone} /><Editor label="Change outcome" title="Update call outcome" fields={[{ name: 'outcome', label: 'Outcome', type: 'select', value: call.outcome, options: ['message', 'blocked', 'connected', 'missed'] }]} command="call.label" initial={{ id }} /><Button variant="outline" onClick={() => setDeleting(!deleting)}>Delete example</Button>{deleting && <div className="inline-confirm"><p>Remove this illustrative call and its transcript from your local review?</p><Button disabled={busy} onClick={async () => { if (await run({ type: 'call.delete', id })) router.push('/demo/calls'); }}>Confirm deletion</Button><Button variant="outline" onClick={() => setDeleting(false)}>Keep call</Button></div>}</Card></div></div></>;
}
function callbackFields(name = '', phone = '+16025550149'): Field[] { return [{ name: 'name', label: 'Name', value: name, maxLength: 100 }, { name: 'phone', label: 'Phone number', type: 'tel', value: phone, hint: phoneHint }, { name: 'scheduledAt', label: 'Date and time (this browser’s timezone)', type: 'datetime-local', hint: 'Saved as an absolute instant and displayed in your workspace timezone.' }, { name: 'note', label: 'What to discuss', type: 'textarea', required: false, maxLength: 500 }]; }
export function CallbackEditor({ name = '', phone = '+16025550149' }: { name?: string; phone?: string }) { const { state } = useReview(); return <Editor label="Schedule callback" title="Make time to reconnect" description="Creates a local reminder. No call is placed or notification delivered." fields={callbackFields(name, phone)} command="callback.create" transform={data => ({ ...data, scheduledAt: new Date(String(data.scheduledAt)).toISOString(), timezone: state.profile.timezone })} />; }
export function Callbacks() {
  const { state, run, busy } = useReview();
  return <><Heading title="Pick up where you left off." description={`Your follow-up list, shown in ${state.profile.timezone}.`}><CallbackEditor /></Heading><Card title="Callbacks">{state.callbacks.length ? <div className="record-list">{state.callbacks.map(item => <article className="record-row" key={item.id}><div><strong>{item.name}</strong><p>{item.phone} · {date(item.scheduledAt, state.profile.timezone)}</p><p>{item.note}</p></div><div className="actions"><Badge tone={item.done ? 'green' : ''}>{item.done ? 'Completed' : 'Scheduled'}</Badge><Button variant="outline" disabled={busy} onClick={() => run({ type: 'callback.toggle', id: item.id })}>{item.done ? 'Reopen' : 'Mark done'}</Button><Confirm label="Remove" title="Remove callback?" description="This removes the local reminder." command={{ type: 'callback.delete', id: item.id }} /></div></article>)}</div> : <Empty title="A clear follow-up list">Schedule a callback from a message or add one here.</Empty>}</Card></>;
}
