'use client';
import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { simulatePolicy } from '@/lib/review/commands';
import { useReview } from './provider';
import { ActionLink, Badge, Card, Confirm, EditForm, Editor, Empty, Fields, formValues, Heading, human, phoneHint, type Field } from './ui';
import type { Destination, LineGrant } from '@/lib/review/model';

export function Screening() {
  const { state } = useReview(); const [result, setResult] = useState<ReturnType<typeof simulatePolicy> | null>(null);
  const scenario: Field[] = [{ name: 'known', label: 'Saved contact', type: 'checkbox' }, { name: 'blocked', label: 'Explicitly blocked', type: 'checkbox' }, { name: 'vip', label: 'VIP contact', type: 'checkbox' }, { name: 'spam', label: 'Flagged as spam', type: 'checkbox' }, { name: 'spamSignal', label: 'Supported spam signal available', type: 'checkbox', value: true }, { name: 'fallbackReady', label: 'Safe fallback tested', type: 'checkbox', value: true }];
  return <><Heading title="Let the right calls through." description="Choose where your assistant steps in. Test the policy before connecting a number." /><div className="workspace-grid equal"><Card title="Your screening policy" subtitle={`Local version ${state.screening.version}`}><EditForm command="screening.save" fields={[{ name: 'mode', label: 'Screening mode', type: 'select', value: state.screening.mode, options: [{ value: 'spam_only', label: 'Spam only — requires reputation support' }, { value: 'unknown', label: 'Unknown callers' }, { value: 'all', label: 'All callers, including contacts' }] }, { name: 'vip', label: 'Allow an explicit VIP exception', type: 'checkbox', value: state.screening.vip }, { name: 'paused', label: 'Pause AI screening and use fallback', type: 'checkbox', value: state.screening.paused, hint: 'Pausing Redial does not undo carrier forwarding.' }, { name: 'maxSeconds', label: 'Maximum screening time (seconds)', type: 'number', min: 30, max: 120, value: state.screening.maxSeconds }]} submit="Save local policy" /></Card><Card title="Try a caller scenario" subtitle="A policy decision, without making a call"><form className="review-form" onSubmit={event => { event.preventDefault(); const values = formValues(event.currentTarget, scenario) as { known: boolean; blocked: boolean; vip: boolean; spam: boolean; spamSignal: boolean; fallbackReady: boolean }; setResult(simulatePolicy(state.screening, values)); }}><Fields fields={scenario} /><Button type="submit">Evaluate scenario</Button></form>{result && <div className="policy-result" role="status"><strong>{result.outcome}</strong><p>{result.reason}</p></div>}</Card></div><Card title="A dependable fallback"><p>Caller ID can be spoofed. Saved contacts and VIP exceptions do not prove identity. A development voice integration must test consent, opt-out, emergencies, voicemail, timeouts and forwarding loops before activation.</p></Card></>;
}
export function Agent() {
  const { state } = useReview();
  return <><Heading title="An assistant that sounds like you." description="Warm, concise, and clear about why it’s answering." /><div className="workspace-grid"><Card title="Personality & instructions" subtitle={`Local draft version ${state.agent.version}`}><EditForm command="agent.save" fields={[{ name: 'name', label: 'Assistant name', value: state.agent.name, maxLength: 80 }, { name: 'voice', label: 'Voice direction', type: 'select', value: state.agent.voice, options: ['Calm', 'Warm', 'Direct'], hint: 'A creative direction for review; no generated audio is available.' }, { name: 'greeting', label: 'Opening greeting', type: 'textarea', value: state.agent.greeting, maxLength: 400 }, { name: 'instructions', label: 'How your assistant should help', type: 'textarea', value: state.agent.instructions, maxLength: 1800, hint: 'Do not include passwords or private information. Instructions never grant tool or routing authority.' }]} /></Card><div className="stack"><Card className="violet-card" title="A considered hello"><p className="greeting-preview">“{state.agent.greeting}”</p><Badge>{state.agent.voice} voice direction</Badge></Card><Card title="The boundaries stay clear"><ul className="plain-list"><li>Disclose that an AI assistant is answering.</li><li>Ask for purpose and urgency without revealing private details.</li><li>Offer an opt-out and an approved fallback.</li><li>Never invent emergency capability or promise a connection.</li></ul><ActionLink href="/demo/live">Try private guidance with Audible</ActionLink></Card></div></div></>;
}
function directoryFields(item?: Destination): Field[] { return [{ name: 'name', label: 'Destination name', value: item?.name, maxLength: 100 }, { name: 'phone', label: 'Phone number', type: 'tel', value: item?.phone || '+16025550149', hint: phoneHint }, { name: 'kind', label: 'Destination type', type: 'select', value: item?.kind || 'phone', options: [{ value: 'phone', label: 'Saved phone' }, { value: 'internal', label: 'Workspace user (simulation)' }, { value: 'extension', label: 'Extension / IVR (provider-gated)' }] }, { name: 'extension', label: 'Extension', value: item?.extension, required: false, maxLength: 8, hint: 'Digits only. Extension routes remain unavailable in the call simulator.' }]; }
export function Directory() {
  const { state, run, busy } = useReview();
  return <><Heading title="The right person, within reach." eyebrow="Directory" description="A considered list of destinations for the next part of the conversation."><Editor title="Add a destination" description="New and edited destinations need explicit local approval before simulation." fields={directoryFields()} command="directory.save" /></Heading><Card title="Saved destinations">{state.directory.length ? <div className="record-list">{state.directory.map(item => <article className="record-row" key={item.id}><div><strong>{item.name}</strong><p>{item.phone}{item.extension && ` · ext. ${item.extension}`}</p><span className="small-label">{human(item.kind)} · version {item.version}</span></div><div className="actions"><Badge tone={item.enabled ? 'green' : ''}>{item.enabled ? 'Approved for simulation' : 'Needs approval'}</Badge><Button variant="outline" disabled={busy} onClick={() => run({ type: 'directory.toggle', id: item.id })}>{item.enabled ? 'Disable' : 'Approve locally'}</Button><Editor label="Edit" title={`Edit ${item.name}`} fields={directoryFields(item)} command="directory.save" initial={{ id: item.id }} /><Confirm label="Remove" title="Remove destination?" description="This removes the saved local destination." command={{ type: 'directory.delete', id: item.id }} /></div></article>)}</div> : <Empty title="A place for trusted destinations">Add a fictional phone number to explore Directory.</Empty>}</Card><div className="workspace-grid equal"><Card title="An answer is not an acceptance"><p>A real transfer needs a verified destination, a bounded attempt and an acceptance step. If the destination is busy or declines, the previous handler retains the caller.</p><ActionLink href="/demo/live">Try a Directory transfer</ActionLink></Card><Card title="Custom routes need another check"><p>Custom dialing, extension navigation, SIP and ring groups require separate authorization and provider capability. They cannot be enabled by a free-form assistant instruction.</p></Card></div></>;
}
export function Contacts() {
  const { state } = useReview(); const [query, setQuery] = useState('');
  const fields = (item?: typeof state.contacts[number]): Field[] => [{ name: 'name', label: 'Name', value: item?.name, maxLength: 100 }, { name: 'phone', label: 'Phone number', type: 'tel', value: item?.phone || '+16025550149', hint: phoneHint }, { name: 'policy', label: 'Call preference', type: 'select', value: item?.policy || 'standard', options: ['standard', 'vip', 'blocked'] }];
  const contacts = state.contacts.filter(item => `${item.name} ${item.phone}`.toLowerCase().includes(query.toLowerCase()));
  return <><Heading title="Familiar voices." description="Keep the people you know close, and set clear preferences for everyone else."><Editor title="Add a contact" fields={fields()} command="contact.save" /></Heading><div className="toolbar"><Input aria-label="Search contacts" placeholder="Search contacts" value={query} onChange={event => setQuery(event.target.value)} /></div><Card title="Your contacts">{contacts.length ? contacts.map(item => <article className="record-row" key={item.id}><span className="avatar">{item.name.split(' ').map(part => part[0]).slice(0, 2).join('')}</span><div className="grow"><strong>{item.name}</strong><p>{item.phone}</p></div><Badge>{item.policy.toUpperCase()}</Badge><Editor label="Edit" title={`Edit ${item.name}`} fields={fields(item)} command="contact.save" initial={{ id: item.id }} /><Confirm label="Remove" title="Remove contact?" description="This removes the contact from this local review." command={{ type: 'contact.delete', id: item.id }} /></article>) : <Empty title="No matching contacts">Try another search or add a contact.</Empty>}</Card></>;
}
const permissionNames: Record<LineGrant, string> = { read_summary: 'Read call summaries', read_transcript: 'Read transcripts', manage_rules: 'Manage screening rules', monitor_live: 'Insider: listen', takeover_live: 'Gavel: take over', direct_agent: 'Audible: guide', transfer_call: 'Directory: transfer' };
export function People() {
  const { state } = useReview();
  return <><Heading title="Shared billing. Personal boundaries." description="Membership and access to a person’s calls are separate decisions."><Editor title="Invite to the example workspace" description="Creates a local invitation record. No email is sent." label="Add person" command="people.invite" fields={[{ name: 'name', label: 'Name', maxLength: 100 }, { name: 'email', label: 'Example email', type: 'email', value: 'person@example.test' }, { name: 'role', label: 'Workspace role', type: 'select', value: 'member', options: ['member', 'billing'] }]} /></Heading><Card title="People & line permissions" subtitle="The illustrative line belongs to Alex. Other adults receive no automatic audio or content access.">{state.people.map(person => <article className="record-row" key={person.id}><span className="avatar">{person.name[0]}</span><div className="grow"><strong>{person.name}</strong><p>{person.email}</p><span className="small-label">{person.grants.length ? person.grants.map(grant => permissionNames[grant]).join(' · ') : 'No line permissions'}</span></div><Badge>{person.role} · {person.status}</Badge>{person.role !== 'owner' && <Editor title={`Alex’s line: ${person.name}`} description="These local grants show the access model; they are not a real authorization service." label="Line permissions" command="people.grants" initial={{ id: person.id }} fields={(Object.keys(permissionNames) as LineGrant[]).map(grant => ({ name: grant, label: permissionNames[grant], type: 'checkbox', value: person.grants.includes(grant) }))} transform={data => ({ grants: Object.keys(data).filter(key => data[key]) })} />}</article>)}</Card><Card title="Access has a purpose"><p>Billing administrators can handle membership without reading another adult’s messages. Support access in production needs a separate, scoped and auditable grant. Live controls require their own permissions and provider checks.</p></Card></>;
}
