'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { Activity, ArrowLeft, AudioLines, BookUser, CalendarClock, CheckCheck, ClipboardList, CreditCard, FileText, Headphones, House, Inbox, LayoutDashboard, ListTodo, Megaphone, Menu, MonitorSmartphone, Network, Phone, Plug, Settings, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { ThemeToggle } from '@/components/theme-toggle';
import { Brand } from '@/components/brand';
import { ReviewProvider } from './provider';

const member = [
  { label: 'Overview', href: '/demo/overview', icon: House }, { label: 'Your submitted setup', href: '/local/account', icon: ClipboardList }, { label: 'Call inbox', href: '/demo/calls', icon: Inbox }, { label: 'Live Call Controls', href: '/demo/live', icon: AudioLines },
  { label: 'Screening', href: '/demo/screening', icon: ShieldCheck }, { label: 'Your assistant', href: '/demo/agent', icon: Sparkles }, { label: 'Directory', href: '/demo/directory', icon: Network },
  { label: 'Contacts', href: '/demo/contacts', icon: BookUser }, { label: 'Callbacks', href: '/demo/callbacks', icon: CalendarClock }, { label: 'Numbers & setup', href: '/demo/numbers', icon: Phone }, { label: 'Connections', href: '/demo/connections', icon: Plug },
  { label: 'People & access', href: '/demo/people', icon: Users }, { label: 'Membership', href: '/demo/billing', icon: CreditCard }, { label: 'Settings', href: '/demo/settings', icon: Settings }, { label: 'Help & support', href: '/demo/help', icon: Headphones }, { label: 'Companion previews', href: '/demo/mobile', icon: MonitorSmartphone },
];
const staff = [
  { label: 'Overview', href: '/demo/ops', icon: LayoutDashboard }, { label: 'Submitted setup review', href: '/local/admin', icon: ClipboardList }, { label: 'Customers', href: '/demo/ops/customers', icon: Users }, { label: 'Revenue', href: '/demo/ops/revenue', icon: CreditCard }, { label: 'Support', href: '/demo/ops/support', icon: Headphones }, { label: 'Voice operations', href: '/demo/ops/voice', icon: Activity }, { label: 'Capabilities', href: '/demo/ops/features', icon: ShieldCheck }, { label: 'CRM pipeline', href: '/demo/ops/crm', icon: BookUser }, { label: 'Campaigns', href: '/demo/ops/campaigns', icon: Megaphone }, { label: 'Content', href: '/demo/ops/content', icon: FileText }, { label: 'AI assistants', href: '/demo/ops/agents', icon: Sparkles }, { label: 'Approvals', href: '/demo/ops/approvals', icon: CheckCheck }, { label: 'Tasks', href: '/demo/ops/tasks', icon: ListTodo }, { label: 'Audit log', href: '/demo/ops/audit', icon: ClipboardList }, { label: 'System settings', href: '/demo/ops/settings', icon: Settings },
];
export function ReviewShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const ops = pathname.startsWith('/demo/ops');
  const [menu, setMenu] = useState(false);
  return <div className={`review-shell ${ops ? 'operations' : ''}`}><aside className="review-sidebar"><div className="sidebar-brand"><Brand /><button className="icon-button review-menu" aria-label={menu ? 'Close workspace menu' : 'Open workspace menu'} aria-expanded={menu} aria-controls="workspace-navigation" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div><nav id="workspace-navigation" aria-label={ops ? 'Operations navigation' : 'Workspace navigation'} className={menu ? 'is-open' : ''} onKeyDown={event => { if (event.key === 'Escape') { setMenu(false); (document.querySelector('.review-menu') as HTMLButtonElement)?.focus(); } }}><p className="nav-caption">{ops ? 'Business operations' : 'Your space'}</p>{(ops ? staff : member).map(item => <Link key={item.href} href={item.href} aria-current={(pathname === item.href || item.href === '/demo/calls' && pathname.startsWith('/demo/calls/')) ? 'page' : undefined} onClick={() => setMenu(false)}><item.icon size={18} strokeWidth={1.7} aria-hidden="true" />{item.label}</Link>)}<div className="sidebar-switch"><Link href={ops ? '/demo/overview' : '/demo/ops'} onClick={() => setMenu(false)}><LayoutDashboard size={18} aria-hidden="true" />{ops ? 'Member workspace' : 'Operations review'}</Link><Link href="/"><ArrowLeft size={18} aria-hidden="true" />Back to website</Link></div></nav><div className="sidebar-profile"><span className="avatar">AM</span><div><strong>Alex Morgan</strong><p>Illustrative workspace</p></div></div></aside><div className="review-body"><header className="review-topbar"><span>{ops ? 'Redial operations' : 'Alex’s workspace'} <span className="badge">Local review</span></span><div className="topbar-actions"><ThemeToggle /><Link href="/demo/onboarding" className="action-link">Setup checklist <ArrowLeft className="flip" size={16} aria-hidden="true" /></Link></div></header><main id="main" tabIndex={-1} className="review-content"><div className="review-disclosure"><span className="status-dot" /><p><strong>Local simulation.</strong> Example data, saved for 8 hours in this browser session. Calls, charges, messages and provider changes are simulated.</p></div><ReviewProvider>{children}</ReviewProvider></main><footer className="review-footer"><span>Made for a quieter day.</span><span>Redial v1.1 · Local review</span></footer></div></div>;
}

