'use client';
import Link from 'next/link';
import { useEffect, useId, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Circle, Headphones, Gavel, MessageSquare, Network, LockKeyhole, Save, ShieldCheck } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Brand } from '@/components/brand';
import { carrierOptions, initialDraft, normalizePhone, validateStep, type OnboardingDraft, type SavedOnboarding } from '@/lib/landing/onboarding';

type Saved = SavedOnboarding;
const titles = [<>Which line should stop <em>ringing?</em></>, <>How should calls <em>reach</em> the agent?</>, <>One small <em>connection.</em></>, <>Make room for a <em>real check.</em></>, <>The <em>voice</em> that answers.</>, <>What it <em>says,</em> and to whom.</>, <>Your quieter day starts <em>here.</em></>];
const descriptions = ['Start with one line. You can add more later, each with its own assistant and rules.', 'Two ways in. Choose the path that suits your phone and the way you want to be reached.', 'Your connection path is saved. Activation comes after number ownership and carrier compatibility are verified.', 'A number on a form is a starting point. Before screening goes live, the complete call path needs to work.', 'Choose the direction for your assistant. Keep it calm, make it warm, or get straight to the point.', 'Your preferences guide the conversation. Every-call mode includes saved contacts.', 'Review your details. Finishing saves your information to your local member account and admin review.'];

function Choice({ value, selected, title, children, tag }: { value: string; selected: string; title: string; children?: React.ReactNode; tag?: string }) {
  const id = useId();
  return <label htmlFor={id} className={`onboard-choice ${selected === value ? 'is-selected' : ''}`}><RadioGroupItem id={id} value={value} aria-describedby={children ? `${id}-description` : undefined} /><span><strong>{title}{tag && <small>{tag}</small>}</strong>{children && <span id={`${id}-description`} className="choice-description">{children}</span>}</span></label>;
}
export function OnboardingForm() {
  const [draft, setDraft] = useState<OnboardingDraft>(initialDraft);
  const [saved, setSaved] = useState<Saved | null>(null);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({}), [message, setMessage] = useState(''), [problem, setProblem] = useState('');
  const [confirmClear, setConfirmClear] = useState(false);
  const form = useRef<HTMLFormElement>(null), heading = useRef<HTMLHeadingElement>(null), lock = useRef(false);
  useEffect(() => {
    let active = true;
    fetch('/api/onboarding').then(async response => { if (!response.ok) throw new Error('Your saved draft could not be loaded. Reload to retry before saving.'); const data = await response.json(); if (active) { if (data.saved) { setSaved(data.saved); setDraft(data.saved.draft); setMessage('Your saved setup is ready to continue.'); } setLoading(false); } }).catch(error => { if (active) { setProblem(error.message); setLoading(false); } });
    return () => { active = false; };
  }, []);
  function update<K extends keyof OnboardingDraft>(key: K, value: OnboardingDraft[K]) {
    setDraft(current => ({ ...current, [key]: value, complete: false })); setErrors(current => ({ ...current, [key]: '' })); setMessage('');
  }
  async function persist(next: OnboardingDraft, notice: string) {
    if (lock.current || loading) return false;
    lock.current = true; setBusy(true); setProblem(''); setMessage('');
    try {
      const response = await fetch('/api/onboarding', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version: saved?.version ?? 0, draft: next }) });
      const data = await response.json();
      if (!response.ok) { if (data.fields) setErrors(data.fields); throw new Error(data.error || 'Your setup could not be saved. Please try again.'); }
      setSaved(data.saved); setDraft(data.saved.draft); setMessage(notice); return true;
    } catch (error) { setProblem(error instanceof Error ? error.message : 'Connection interrupted. Reload to check the saved draft before retrying.'); return false; }
    finally { lock.current = false; setBusy(false); }
  }
  async function advance() {
    const nextErrors = validateStep(draft, draft.step); setErrors(nextErrors);
    if (Object.keys(nextErrors).length) { const name = Object.keys(nextErrors)[0]; form.current?.querySelector<HTMLElement>(`#setup-${name}`)?.focus(); return; }
    const next = { ...draft, step: Math.min(7, draft.step + 1), complete: draft.step === 7 };
    if (await persist(next, draft.step === 7 ? 'Your setup is saved in your local account and admin review.' : 'Progress saved on this computer.')) { heading.current?.focus({ preventScroll: true }); heading.current?.scrollIntoView({ block: 'start', behavior: 'instant' }); }
  }
  async function clear() {
    if (lock.current) return; lock.current = true; setBusy(true); setProblem('');
    try { const response = await fetch('/api/onboarding', { method: 'DELETE' }); if (!response.ok) throw new Error('Your saved draft could not be deleted.'); setSaved(null); setDraft(initialDraft); setErrors({}); setMessage('Your local setup information has been deleted.'); setConfirmClear(false); }
    catch (error) { setProblem(error instanceof Error ? error.message : 'Please try again.'); }
    finally { lock.current = false; setBusy(false); }
  }
  function fieldError(name: string) { return errors[name] ? <span className="onboard-field-error" id={`setup-${name}-error`}>{errors[name]}</span> : null; }
  function input(name: 'fullName' | 'email' | 'phone' | 'providerName', label: string, type = 'text', placeholder = '', autocomplete?: string) {
    return <div className="onboard-field"><label htmlFor={`setup-${name}`}>{label}</label><Input id={`setup-${name}`} name={name} type={type} autoComplete={autocomplete} placeholder={placeholder} value={draft[name]} maxLength={name === 'email' ? 180 : name === 'phone' ? 30 : 100} onChange={event => update(name, event.target.value)} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name] ? `setup-${name}-error` : undefined} />{fieldError(name)}</div>;
  }
  const completed = draft.complete;
  return <div className="onboard-card" data-step={draft.step} data-complete={String(completed)}>
    <div className="onboard-header"><Brand /><button className="onboard-save" disabled={busy || loading || completed} type="button" onClick={() => persist(draft, saved?.submission ? 'Changes saved as a draft. Finish setup to update both account views.' : 'Saved. Return in this browser within 8 hours to finish your setup.')}><Save size={14} aria-hidden="true" /><span>Save and finish later</span></button></div>
    <ol className="onboard-progress" aria-label="Setup progress">{titles.map((_, index) => <li key={index} aria-label={`Step ${index + 1}${draft.step === index + 1 ? ', current' : draft.step > index + 1 ? ', saved' : ''}`} aria-current={draft.step === index + 1 ? 'step' : undefined} className={index < draft.step ? 'filled' : ''} />)}</ol>
    <p className="onboard-step-label">{completed ? 'YOUR NEXT CHAPTER' : `STEP ${draft.step} OF 7`}</p>
    <h2 ref={heading} tabIndex={-1}>{completed ? <>A little more <em>intention.</em></> : titles[draft.step - 1]}</h2>
    <p className="onboard-description">{completed ? saved?.submission ? 'Your information is saved in your local member account and admin review. Your number is not connected yet; verification and a real test call come before activation.' : 'Your earlier local draft is saved. Review and finish setup to add it to your member account and admin review.' : descriptions[draft.step - 1]}</p>
    {loading && <p role="status" className="onboard-message">Checking for a saved setup…</p>}
    {problem && <div role="alert" className="onboard-error">{problem}</div>}
    {message && <p role="status" className="onboard-message"><CheckCircle2 size={16} aria-hidden="true" />{message}</p>}
    {completed ? <><div className="onboard-complete"><CheckCircle2 size={34} strokeWidth={1.4} /><div><strong>Saved for {draft.fullName}</strong><p>{draft.email} · {draft.phone}</p><span>Reference {saved?.id.slice(0, 8).toUpperCase()} · {saved?.submission ? 'saved until you delete it' : 'draft expires after 8 hours'}</span></div></div>{saved?.submission && <div className="onboard-handoff"><span><CheckCircle2 size={17} />Member account updated</span><span><CheckCircle2 size={17} />Admin review updated</span><Link href="/local/admin">Open local admin dashboard <ArrowRight size={14} /></Link></div>}<ControlGuide /><div className="onboard-actions"><button className="onboard-back" onClick={() => { setDraft(current => ({ ...current, complete: false, acknowledgeLocal: false })); setMessage(''); }}><ArrowLeft size={15} />Review details</button>{saved?.submission && <Link className="onboard-next" href="/local/account">Open my local account <ArrowRight size={16} /></Link>}</div></> : <form ref={form} noValidate onSubmit={event => { event.preventDefault(); void advance(); }}>
      <fieldset className="onboard-fields" disabled={busy || loading}>
      {draft.step === 1 && <><div className="onboard-field-pair">{input('fullName', 'Your name', 'text', 'Alex Morgan', 'name')}{input('email', 'Your email', 'email', 'you@example.com', 'email')}</div>{input('phone', 'The number people call you on', 'tel', '(480) 555-0142', 'tel-national')}<fieldset className="onboard-options"><legend>What kind of line is it?</legend><RadioGroup name="lineType" aria-label="What kind of line is it?" value={draft.lineType} onValueChange={value => update('lineType', value as OnboardingDraft['lineType'])}><div className="onboard-options-row"><Choice value="personal" selected={draft.lineType} title="Personal">My own cell.</Choice><Choice value="business" selected={draft.lineType} title="Business">Customers call it.</Choice></div></RadioGroup></fieldset><div className="onboard-field"><label htmlFor="setup-carrier">Who’s your carrier?</label><p>Your carrier and plan determine which connection options can be verified.</p><Select id="setup-carrier" name="carrier" value={draft.carrier} placeholder="Select your carrier" options={carrierOptions} aria-invalid={Boolean(errors.carrier)} aria-describedby={errors.carrier ? "setup-carrier-error" : undefined} onValueChange={value => update("carrier", value as OnboardingDraft["carrier"])} />{fieldError('carrier')}</div></>}
      {draft.step === 2 && <><fieldset className="onboard-options"><legend className="sr-only">How calls reach Redial</legend><RadioGroup name="connection" aria-label="How calls reach Redial" value={draft.connection} onValueChange={value => update('connection', value as OnboardingDraft['connection'])}><Choice value="conditional" selected={draft.connection} title="Forward what I don’t answer" tag="KEEP YOUR NUMBER">Your phone may ring first. On a compatible setup, missed or busy calls go to your assistant. Your number stays the same.</Choice><Choice value="dedicated" selected={draft.connection} title="Give me a screened number">A separate number that the assistant can answer first. Share it for business, deliveries, listings, or a little more privacy.</Choice></RadioGroup></fieldset><div className="onboard-note"><span aria-hidden="true">◆</span><p>{draft.connection === 'conditional' ? <><strong>Forwarding can change which voicemail answers.</strong> Carrier support and undo steps must be confirmed before enabling a route.</> : <><strong>A dedicated number needs provisioning.</strong> Availability, eligibility and pricing are confirmed before any number is assigned.</>}</p></div></>}
      {draft.step === 3 && <><div className="onboard-connection-card"><p className="onboard-step-label">{draft.connection === 'conditional' ? 'CONDITIONAL FORWARDING' : 'DEDICATED NUMBER'} · {draft.carrier}</p><div className="onboard-route"><span>Your caller</span><ArrowRight size={19} /><span>Redial</span><ArrowRight size={19} /><span>You decide</span></div><h3>{draft.connection === 'conditional' ? 'Keep your number. Add a first response.' : 'A new front door for your calls.'}</h3><p>{draft.connection === 'conditional' ? 'Your number’s route will be checked before any forwarding instructions appear. There is no carrier code to dial in this local setup.' : 'We’ll save your preference for a dedicated number. No number is purchased or reserved by this form.'}</p><span className="onboard-status"><Circle size={12} /> Activation not connected</span></div><label className="onboard-checkbox"><Checkbox id="setup-connectionReviewed" name="connectionReviewed" checked={draft.connectionReviewed} onCheckedChange={value => update('connectionReviewed', value === true)} aria-invalid={Boolean(errors.connectionReviewed)} aria-describedby={errors.connectionReviewed ? 'setup-connectionReviewed-error' : undefined} /><span>I understand this saves my connection preference. Activation happens after verification.</span></label>{fieldError('connectionReviewed')}</>}
      {draft.step === 4 && <><div className="onboard-checks"><div><Check size={19} /><span><strong>Phone number format checked</strong><small>{normalizePhone(draft.phone)}</small></span><b>VALID</b></div><div><Circle size={16} /><span><strong>Carrier route and fallback test</strong><small>Requires a connected development service</small></span><b>PENDING</b></div><div><Circle size={16} /><span><strong>Assistant answers and returns a transcript</strong><small>Requires an actual, authorized test call</small></span><b>PENDING</b></div></div><div className="onboard-note"><ShieldCheck size={18} /><p><strong>Test the full path before switching on.</strong> Number format validation does not prove ownership, forwarding or service compatibility.</p></div><label className="onboard-checkbox"><Checkbox id="setup-checksReviewed" name="checksReviewed" checked={draft.checksReviewed} onCheckedChange={value => update('checksReviewed', value === true)} aria-invalid={Boolean(errors.checksReviewed)} aria-describedby={errors.checksReviewed ? 'setup-checksReviewed-error' : undefined} /><span>I’ll complete the route and fallback checks before activation.</span></label>{fieldError('checksReviewed')}</>}
      {draft.step === 5 && <><fieldset className="onboard-options"><legend className="sr-only">Assistant connection preference</legend><RadioGroup name="provider" aria-label="Assistant connection preference" value={draft.provider} onValueChange={value => update('provider', value as OnboardingDraft['provider'])}><Choice value="redial" selected={draft.provider} title="Redial’s assistant" tag="PROPOSED xAI STACK">A guided setup with the planned Redial voice service. Availability is confirmed before connection.</Choice><Choice value="own" selected={draft.provider} title="I’d like to bring my own assistant">Tell us your provider preference. Compatibility still needs review; no API keys are collected here.</Choice></RadioGroup></fieldset>{draft.provider === 'own' && input('providerName', 'Preferred voice provider', 'text', 'Your provider’s name')}<fieldset className="onboard-options"><legend>How should your assistant feel?</legend><RadioGroup name="voice" aria-label="How should your assistant feel?" value={draft.voice} onValueChange={value => update('voice', value as OnboardingDraft['voice'])}><div className="onboard-voice-options">{(['Calm', 'Warm', 'Direct'] as const).map(voice => <Choice key={voice} value={voice} selected={draft.voice} title={voice} />)}</div></RadioGroup></fieldset></>}
      {draft.step === 6 && <><fieldset className="onboard-options"><legend>Who gets screened</legend><RadioGroup name="screening" aria-label="Who gets screened" value={draft.screening} onValueChange={value => update('screening', value as OnboardingDraft['screening'])}><Choice value="unknown" selected={draft.screening} title="Unknown callers" tag="A CONSIDERED START">Ask for context from callers outside your saved contacts, when the supported route allows it.</Choice><Choice value="spam_only" selected={draft.screening} title="Spam-labeled calls only">Requires a supported reputation signal. Unknown numbers aren’t automatically treated as spam.</Choice><Choice value="all" selected={draft.screening} title="Every call">Even saved contacts are greeted, unless you explicitly enable a VIP exception.</Choice></RadioGroup></fieldset><div className="onboard-field"><label htmlFor="setup-greeting">Opening line</label><p>Introduce the AI assistant, then invite the caller to share why they’re calling.</p><Textarea id="setup-greeting" name="greeting" rows={4} maxLength={400} value={draft.greeting} onChange={event => update('greeting', event.target.value)} aria-invalid={Boolean(errors.greeting)} aria-describedby={errors.greeting ? 'setup-greeting-error' : undefined} />{fieldError('greeting')}<span className="onboard-character-count">{draft.greeting.length} / 400</span></div></>}
      {draft.step === 7 && <><dl className="onboard-review"><div><dt>Your details</dt><dd>{draft.fullName}<span>{draft.email}</span></dd></div><div><dt>Your line</dt><dd>{draft.phone}<span>{draft.carrier} · {draft.lineType}</span></dd></div><div><dt>Your connection</dt><dd>{draft.connection === 'conditional' ? 'Conditional forwarding' : 'Dedicated number'}<span>Pending verification</span></dd></div><div><dt>Your assistant</dt><dd>{draft.provider === 'redial' ? 'Redial assistant' : draft.providerName}<span>{draft.voice} · {draft.screening === 'all' ? 'All callers' : draft.screening === 'unknown' ? 'Unknown callers' : 'Spam-labeled calls'}</span></dd></div></dl><ControlGuide /><label className="onboard-checkbox"><Checkbox id="setup-acknowledgeLocal" name="acknowledgeLocal" checked={draft.acknowledgeLocal} onCheckedChange={value => update('acknowledgeLocal', value === true)} aria-invalid={Boolean(errors.acknowledgeLocal)} aria-describedby={errors.acknowledgeLocal ? 'setup-acknowledgeLocal-error' : undefined} /><span>Save my details on this computer in my local member account and admin review until I delete them. Live sign-in, email and service activation are not connected.</span></label>{fieldError('acknowledgeLocal')}</>}
      </fieldset>
      <div className="onboard-actions">{draft.step > 1 ? <button type="button" className="onboard-back" disabled={busy} onClick={() => { setDraft(current => ({ ...current, step: current.step - 1 })); setErrors({}); setMessage(''); heading.current?.focus({ preventScroll: true }); }}><ArrowLeft size={15} />Back</button> : <span className="onboard-private"><LockKeyhole size={13} />A personal beginning.</span>}<button className="onboard-next" type="submit" disabled={busy || loading}>{busy ? 'Saving…' : draft.step === 7 ? 'Finish setup' : 'Continue'}<ArrowRight size={16} aria-hidden="true" /></button></div>
    </form>}
    <div className="onboard-local-footer"><span><LockKeyhole size={12} />Local setup · no service activation</span>{saved && <button type="button" disabled={busy} onClick={() => setConfirmClear(!confirmClear)}>Delete saved details</button>}</div>
    {confirmClear && <div className="onboard-delete-confirm"><p>Delete your saved setup information and remove it from both account views?</p><button disabled={busy} onClick={clear}>Delete my saved setup</button><button onClick={() => setConfirmClear(false)}>Keep it</button></div>}
  </div>;
}
function ControlGuide() { return <div className="onboard-control-guide">{[{ name: 'Insider', title: 'Listen without speaking', icon: Headphones }, { name: 'Gavel', title: 'Make the conversation yours', icon: Gavel }, { name: 'Audible', title: 'Give your assistant a private word', icon: MessageSquare }, { name: 'Directory', title: 'Connect the right person', icon: Network }].map(control => <div key={control.name}><control.icon size={17} /><strong>{control.name}</strong><span>{control.title}</span></div>)}<p>Live controls require a supported connection, the right permissions and completed setup checks.</p></div>; }

