import { ArrowDownLeft, ArrowRight, AudioLines, Check, CheckCheck, ChevronRight, FileText, Gavel, Headphones, LockKeyhole, MessageSquare, MicOff, Phone, PhoneOff, Signal, Sparkles, Users, Wifi } from 'lucide-react';
import type { CSSProperties } from 'react';
import { clamp, smooth, timeline } from '@/lib/landing/timeline';
import { sampleCall, sampleTurnAt } from '@/lib/landing/story-demo';

const reveal = (position: number, chapter: number, delay = 0, duration = .22): CSSProperties => {
  const amount = smooth((position - chapter + .08 - delay) / duration);
  return { opacity: amount, transform: `translate3d(0,${(1 - amount) * 19}px,0) scale(${.96 + amount * .04})`, filter: `blur(${(1 - amount) * 4}px)` };
};

/** Two independently scrubbed layers keep screen changes continuous in reverse. */
export function PhoneDisplay({ position, guidance, sampleTime }: { position: number; guidance?: string; sampleTime?: number }) {
  const chapter = Math.min(8, Math.floor(position)), next = Math.min(8, chapter + 1);
  const blend = chapter < 8 ? smooth((position - chapter - .73) / .27) : 0;
  return <div className="phone-display" data-screen-chapter={chapter}>
    <div className="phone-screen-layer" style={{ opacity: 1 - blend, transform: `translate3d(0,${-blend * 65}px,0) scale(${1 - blend * .06})`, filter: `blur(${blend * 7}px)` }}><PhoneScreen chapter={chapter} position={position} guidanceText={guidance} sampleTime={sampleTime} /></div>
    {blend > 0 && <div className="phone-screen-layer" style={{ opacity: blend, transform: `translate3d(0,${(1 - blend) * 100}px,0) scale(${.95 + blend * .05})`, filter: `blur(${(1 - blend) * 7}px)` }}><PhoneScreen chapter={next} position={Math.max(next, position)} guidanceText={guidance} sampleTime={sampleTime} /></div>}
    <div className="phone-glass-reflection" /><div className="phone-glass-edge" />
  </div>;
}

const controls = [{ name: 'Insider', icon: Headphones }, { name: 'Gavel', icon: Gavel }, { name: 'Audible', icon: MessageSquare }, { name: 'Directory', icon: Users }];
export function PhoneScreen({ chapter, position, guidanceText, sampleTime }: { chapter: number; position: number; guidanceText?: string; sampleTime?: number }) {
  const guidance = guidanceText ?? 'Ask whether 10 AM works.';
  const active = chapter === 3 ? 'Insider' : chapter === 4 ? 'Audible' : chapter === 5 ? 'Gavel' : chapter === 6 ? 'Directory' : '';
  const phase = clamp(position - chapter), frame = timeline(position / 9);
  const toneStyle = { '--phone-phase': phase, '--phone-energy': Math.sin(position * 17), '--phone-tint': frame.tone.join(' '), '--phone-orbit': `${position * 85}deg` } as CSSProperties;
  return <div className={`story-phone-ui screen-${chapter}`} style={toneStyle}><div className="phone-system-bar"><span>9:41</span><span className="phone-island" /><span><Signal size={12} /><Wifi size={12} /><i /></span></div>
    {chapter === 0 ? <div className="incoming-screen"><p className="phone-mono">INCOMING CALL</p><div className="caller-orbit"><span /><span /><div>J</div></div><h3>Jordan Miller</h3><p>Unknown number</p><span className="phone-number">(480) 555-0142</span><div className="incoming-note"><Sparkles size={17} /><span>A little context<br /><strong>before you answer.</strong></span></div><div className="phone-call-buttons"><span><i><PhoneOff size={22} /></i>Decline</span><span><i><Phone size={22} /></i>Answer</span></div><div className="phone-home-line" /></div> : chapter === 8 ? <div className="phone-setup-preview"><div className="phone-wordmark">R <span>Redial</span></div><div className="phone-progress"><i /><i /><i /><i /><i /><i /><i /></div><p className="phone-mono">STEP 1 OF 7</p><h3>Which line should<br />stop <em>ringing?</em></h3><p>A little more quiet starts with you.</p><div className="preview-field">Your name<span>Alex Morgan</span></div><div className="preview-field">The number people call<span>(480) 555-0142</span></div><div className="preview-choices"><span>◉ Personal</span><span>○ Business</span></div><div className="preview-continue">Let’s begin <ArrowRight size={15} /></div></div> : <>
      <div className="phone-app-header"><div className="phone-wordmark">R <span>Redial</span></div><span className="phone-example-tag">Example</span></div>
      <div className="phone-caller-heading"><span className="small-caller">J</span><div><strong>Jordan Miller</strong><p>{chapter >= 7 ? 'Call complete · 2 min' : 'Delivery · incoming call'}</p></div><span className="phone-state-dot" /></div>
      {chapter === 1 && <div className="phone-screening-state"><div className="assistant-orb"><AudioLines size={32} strokeWidth={1} /></div><p className="phone-mono">REDIAL IS ANSWERING</p><h3 style={reveal(position, chapter)}>A thoughtful<br />first hello.</h3><p style={reveal(position, chapter, .13)}>“Hi, I’m Alex’s AI assistant.<br />How can I help you today?”</p><Waveform position={position} /><span className="phone-caption">Introducing the assistant</span></div>}
      {[2, 3, 4].includes(chapter) && <><div className="phone-conversation-label"><span className="phone-state-dot" />{chapter === 3 ? 'Insider · listening' : 'Live transcript'}<span>Illustrative</span></div><div className="phone-transcript">{sampleTime !== undefined && chapter !== 4 ? <PhoneTranscriptMessages time={sampleTime} /> : <><div className="phone-bubble agent" style={chapter === 2 ? reveal(position, chapter) : undefined}><span>REDIAL</span><p>Hi, I’m Alex’s AI assistant. What’s your call about?</p></div><div className="phone-bubble caller" style={chapter === 2 ? reveal(position, chapter, .08) : undefined}><span>JORDAN</span><p>{'I have a delivery for Alex. Would tomorrow morning work?'.split(' ').map((word, index) => <span key={index} style={{ opacity: chapter === 2 ? .15 + .85 * smooth((phase - index * .022) / .08) : 1 }}>{word} </span>)}</p></div></>}{chapter === 2 && <div className="transcript-typing">{[0, 1, 2].map(index => <i key={index} style={{ opacity: .3 + Math.abs(Math.sin(position * 20 + index)) * .7, transform: `translateY(${Math.sin(position * 20 + index) * 2}px)` }} />)}<span>Making room for context…</span></div>}{chapter === 3 && <div className="insider-panel" style={reveal(position, chapter, .12)}><Headphones size={20} /><strong>You’re listening.</strong><Waveform position={position} /><span><MicOff size={12} /> Your microphone stays off</span></div>}{chapter === 4 && <div className="audible-panel" style={reveal(position, chapter)}><span><LockKeyhole size={12} /> ONLY TO YOUR ASSISTANT</span><p>{guidanceText ?? guidance.slice(0, Math.max(0, Math.ceil(clamp((phase + .03) / .34) * guidance.length)))}<i className="guidance-caret" /></p><div style={guidanceText ? undefined : reveal(position, chapter, .38, .12)}><CheckCheck size={13} /> Example guidance delivered</div><i className="guidance-delivery" style={{ transform: `scaleX(${smooth((phase - .25) / .22)})` }} /></div>}</div></>}
      {chapter === 5 && <div className="handoff-screen"><div className="handoff-icons"><span style={{ opacity: 1 - smooth((phase - .1) / .18) * .8, transform: `scale(${1 - smooth((phase - .1) / .18) * .16})` }}><Sparkles size={24} /></span><ArrowRight size={20} /><span style={{ boxShadow: `0 0 ${smooth((phase - .25) / .2) * 28}px rgb(134 223 187 / .3)` }}><Phone size={24} /></span></div><p className="phone-mono">GAVEL · TAKE OVER</p><h3>Your voice.<br />Your conversation.</h3><div className="handoff-step" style={reveal(position, chapter, .05, .12)}><Check size={15} /><span>Your connection is ready</span></div><div className="handoff-step" style={reveal(position, chapter, .21, .12)}><Check size={15} /><span>AI stopped and removed</span></div><div className="handoff-active" style={reveal(position, chapter, .40, .12)}><span className="phone-state-dot" /> You’re speaking with Jordan</div><div style={reveal(position, chapter, .40, .12)}><Waveform position={position} /></div><p className="phone-caption">Illustrative handoff · scroll through each step</p></div>}
      {chapter === 6 && <div className="directory-screen"><p className="phone-mono">DIRECTORY · TRANSFER</p><h3>A good next<br />connection.</h3><div className="destination-card" style={reveal(position, chapter)}><span className="small-caller">S</span><div><strong>Sam · Office reception</strong><p>Approved destination</p></div><ChevronRight size={16} /></div><div className="transfer-path"><span /><i style={{ '--route-fill': smooth(phase / .18) } as CSSProperties} /><span /><i style={{ '--route-fill': smooth((phase - .18) / .18) } as CSSProperties} /><span style={{ opacity: .3 + .7 * smooth((phase - .28) / .15) }} /></div><div className="transfer-labels"><span>Caller</span><span>Redial</span><span>Sam</span></div><div className="handoff-step" style={reveal(position, chapter, .36, .12)}><Check size={15} /><span>Sam accepts the connection</span></div><div className="handoff-active" style={reveal(position, chapter, .50, .12)}><span className="phone-state-dot" /> The conversation continues</div><p className="phone-caption">Example onward transfer after Gavel</p></div>}
      {chapter === 7 && <div className="summary-screen"><span className="summary-icon" style={reveal(position, chapter)}><FileText size={26} /></span><p className="phone-mono">ALL THE CONTEXT YOU NEED</p><h3>A delivery.<br />A clear next step.</h3><div className="summary-note" style={reveal(position, chapter, .10)}><strong>The short version</strong><p>Jordan called about a delivery. Alex took over, then connected Jordan with Sam at reception.</p><span><ArrowDownLeft size={13} /> Incoming · today, 9:41 AM</span></div><div className="summary-link" style={reveal(position, chapter, .23)}><FileText size={15} /> Read the transcript <ChevronRight size={14} /></div><div className="summary-link" style={reveal(position, chapter, .32)}><Phone size={15} /> Plan a callback <ChevronRight size={14} /></div></div>}
      {chapter < 7 && <div className="phone-control-bar">{controls.map(control => <div key={control.name} className={active === control.name ? 'selected' : ''}><control.icon size={17} strokeWidth={1.7} /><span>{control.name}</span></div>)}</div>}
      <div className="phone-home-line" />
    </>}
  </div>;
}
export function Waveform({ position }: { position: number }) { return <div className="story-waveform">{Array.from({ length: 27 }, (_, index) => <i key={index} style={{ height: `${7 + Math.abs(Math.sin(index * .67 + position * 6)) * (index > 5 && index < 23 ? 24 : 10)}px` }} />)}</div>; }


function PhoneTranscriptMessages({ time }: { time: number }) {
  const active = sampleTurnAt(time);
  return <>{sampleCall.turns.slice(Math.max(0, active - 1), active + 1).map(turn => <div className={`phone-bubble sample-phone-bubble ${turn.speaker === 'agent' ? 'agent' : 'caller'}`} key={turn.start}><span>{turn.label.toUpperCase()}</span><p>{turn.text}</p></div>)}</>;
}
