import {test,expect} from '@playwright/test';
test('verified session, workspace creation, persistent records, mobile navigation and revocation',async({page,request})=>{
  await request.post('http://127.0.0.1:3213/__test/reset');
  await page.goto('/sign-in');
  await page.getByLabel('Email',{exact:true}).fill('review@example.test');
  await page.getByLabel('Password',{exact:true}).fill('A-long-test-password!');
  await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.getByRole('heading',{name:'A space for your calls.'})).toBeVisible();
  await page.getByLabel('Workspace name').fill('Review business');
  await page.getByLabel('Workspace type').click();await page.getByRole('option',{name:'business',exact:true}).click();
  await page.getByRole('button',{name:'Create workspace',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Contacts',exact:true}).click();
  await page.getByLabel('Name',{exact:true}).fill('Test contact');
  await page.getByLabel('International phone number',{exact:true}).fill('+442071234567');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByText('Test contact',{exact:true})).toBeVisible();
  await page.reload();await page.getByText('Test contact',{exact:true}).click();
  await expect(page.getByLabel('Name',{exact:true}).last()).toHaveValue('Test contact');
  await page.getByLabel('Name',{exact:true}).last().fill('Updated contact');
  await page.getByRole('button',{name:'Save changes'}).click();
  await expect(page.getByText('Updated contact',{exact:true})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Menu',exact:true}).click();
  await page.getByRole('link',{name:'Screening',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Screening',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByRole('button',{name:'Save changes'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/dashboard-member-mobile.png'});
  await page.setViewportSize({width:1440,height:900});await page.screenshot({path:'test-results/dashboard-member-desktop.png'});
  await page.goto('/ops');await expect(page).toHaveURL(/staff-sign-in/);
  await request.post('http://127.0.0.1:3213/__test/revoke');
  await page.goto('/app');await expect(page).toHaveURL(/sign-in/);
});
test('database errors never fall back to demo content',async({page,request})=>{
  await request.post('http://127.0.0.1:3213/__test/reset');
  await page.goto('/sign-in');await page.getByLabel('Email',{exact:true}).fill('review@example.test');await page.getByLabel('Password',{exact:true}).fill('A-long-test-password!');await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.getByRole('heading',{name:'A space for your calls.'})).toBeVisible();
  await request.post('http://127.0.0.1:3213/__test/offline');
  await page.goto('/app');await expect(page.getByRole('heading',{name:'Workspace data is unavailable'})).toBeVisible();await expect(page.getByText('Jordan Miller')).toHaveCount(0);
});
