import { ArrowDownLeft, ArrowRight, AudioLines, Check, CheckCheck, ChevronRight, FileText, Gavel, Headphones, LockKeyhole, MessageSquare, MicOff, Phone, PhoneOff, Signal, Sparkles, Users, Wifi } from 'lucide-react';
import { clamp } from '@/lib/landing/timeline';

const controls = [{ name: 'Insider', icon: Headphones }, { name: 'Gavel', icon: Gavel }, { name: 'Audible', icon: MessageSquare }, { name: 'Directory', icon: Users }];
export function PhoneScreen({ chapter, position }: { chapter: number; position: number }) {
  const active = chapter === 3 ? 'Insider' : chapter === 4 ? 'Audible' : chapter === 5 ? 'Gavel' : chapter === 6 ? 'Directory' : '';
  return <div className={`story-phone-ui screen-${chapter}`}><div className="phone-system-bar"><span>9:41</span><span className="phone-island" /><span><Signal size={12} /><Wifi size={12} /><i /></span></div>
    {chapter === 0 ? <div className="incoming-screen"><p className="phone-mono">INCOMING CALL</p><div className="caller-orbit"><span /><span /><div>J</div></div><h3>Jordan Miller</h3><p>Unknown number</p><span className="phone-number">(480) 555-0142</span><div className="incoming-note"><Sparkles size={17} /><span>A little context<br /><strong>before you answer.</strong></span></div><div className="phone-call-buttons"><span><i><PhoneOff size={22} /></i>Decline</span><span><i><Phone size={22} /></i>Answer</span></div><div className="phone-home-line" /></div> : chapter === 8 ? <div className="phone-setup-preview"><div className="phone-wordmark">R <span>Redial</span></div><div className="phone-progress"><i /><i /><i /><i /><i /><i /><i /></div><p className="phone-mono">STEP 1 OF 7</p><h3>Which line should<br />stop <em>ringing?</em></h3><p>A little more quiet starts with you.</p><div className="preview-field">Your name<span>Alex Morgan</span></div><div className="preview-field">The number people call<span>(480) 555-0142</span></div><div className="preview-choices"><span>◉ Personal</span><span>○ Business</span></div><div className="preview-continue">Let’s begin <ArrowRight size={15} /></div></div> : <>
      <div className="phone-app-header"><div className="phone-wordmark">R <span>Redial</span></div><span className="phone-example-tag">Example</span></div>
      <div className="phone-caller-heading"><span className="small-caller">J</span><div><strong>Jordan Miller</strong><p>{chapter >= 7 ? 'Call complete · 2 min' : 'Delivery · incoming call'}</p></div><span className="phone-state-dot" /></div>
      {chapter === 1 && <div className="phone-screening-state"><div className="assistant-orb"><AudioLines size={32} strokeWidth={1} /></div><p className="phone-mono">REDIAL IS ANSWERING</p><h3>A thoughtful<br />first hello.</h3><p>“Hi, I’m Alex’s AI assistant.<br />How can I help you today?”</p><Waveform position={position} /><span className="phone-caption">Introducing the assistant</span></div>}
      {[2, 3, 4].includes(chapter) && <><div className="phone-conversation-label"><span className="phone-state-dot" />{chapter === 3 ? 'Insider · listening' : 'Live transcript'}<span>Illustrative</span></div><div className="phone-transcript"><div className="phone-bubble agent"><span>REDIAL</span><p>Hi, I’m Alex’s AI assistant. What’s your call about?</p></div><div className="phone-bubble caller" style={{ opacity: chapter === 2 ? clamp((position - 2) * 4 + .3) : 1, transform: `translateY(${chapter === 2 ? 14 * (1 - clamp((position - 2) * 4)) : 0}px)` }}><span>JORDAN</span><p>I have a delivery for Alex. Would tomorrow morning work?</p></div>{chapter === 2 && <div className="transcript-typing"><i /><i /><i /><span>Making room for context…</span></div>}{chapter === 3 && <div className="insider-panel"><Headphones size={20} /><strong>You’re listening.</strong><Waveform position={position} /><span><MicOff size={12} /> Your microphone stays off</span></div>}{chapter === 4 && <div className="audible-panel"><span><LockKeyhole size={12} /> ONLY TO YOUR ASSISTANT</span><p>Ask whether 10 AM works.</p><div><CheckCheck size={13} /> Example guidance delivered</div></div>}</div></>}
      {chapter === 5 && <div className="handoff-screen"><div className="handoff-icons"><span><Sparkles size={24} /></span><ArrowRight size={20} /><span><Phone size={24} /></span></div><p className="phone-mono">GAVEL · TAKE OVER</p><h3>Your voice.<br />Your conversation.</h3><div className="handoff-step"><Check size={15} /><span>Your connection is ready</span></div><div className="handoff-step"><Check size={15} /><span>AI stopped and removed</span></div><div className="handoff-active"><span className="phone-state-dot" /> You’re speaking with Jordan</div><Waveform position={position} /><p className="phone-caption">Illustrative completed handoff</p></div>}
      {chapter === 6 && <div className="directory-screen"><p className="phone-mono">DIRECTORY · TRANSFER</p><h3>A good next<br />connection.</h3><div className="destination-card"><span className="small-caller">S</span><div><strong>Sam · Office reception</strong><p>Approved destination</p></div><ChevronRight size={16} /></div><div className="transfer-path"><span /><i /><span /><i /><span /></div><div className="transfer-labels"><span>Caller</span><span>Redial</span><span>Sam</span></div><div className="handoff-step"><Check size={15} /><span>Sam accepts the connection</span></div><div className="handoff-active"><span className="phone-state-dot" /> The conversation continues</div><p className="phone-caption">Example onward transfer after Gavel</p></div>}
      {chapter === 7 && <div className="summary-screen"><span className="summary-icon"><FileText size={26} /></span><p className="phone-mono">ALL THE CONTEXT YOU NEED</p><h3>A delivery.<br />A clear next step.</h3><div className="summary-note"><strong>The short version</strong><p>Jordan called about a delivery. Alex took over, then connected Jordan with Sam at reception.</p><span><ArrowDownLeft size={13} /> Incoming · today, 9:41 AM</span></div><div className="summary-link"><FileText size={15} /> Read the transcript <ChevronRight size={14} /></div><div className="summary-link"><Phone size={15} /> Plan a callback <ChevronRight size={14} /></div></div>}
      {chapter < 7 && <div className="phone-control-bar">{controls.map(control => <div key={control.name} className={active === control.name ? 'selected' : ''}><control.icon size={17} strokeWidth={1.7} /><span>{control.name}</span></div>)}</div>}
      <div className="phone-home-line" />
    </>}
  </div>;
}
export function Waveform({ position }: { position: number }) { return <div className="story-waveform">{Array.from({ length: 27 }, (_, index) => <i key={index} style={{ height: `${7 + Math.abs(Math.sin(index * .67 + position * 6)) * (index > 5 && index < 23 ? 24 : 10)}px` }} />)}</div>; }
