import Link from 'next/link';
import { authAction } from '@/lib/supabase/actions';
import { Brand } from './brand';
import { Button } from './ui/button';
import { Input } from './ui/input';

const notices: Record<string, string> = { invalid: 'Enter a valid email and a password with at least 12 characters.', failed: 'That request could not be completed. Check your details and try again.', email: 'If your address is eligible, check your inbox for the next step.', origin: 'Open this form from the configured Redial domain.', expired: 'This link has expired or is invalid. Request a new one.' };
export function AccountSignIn({ staff = false, notice = '', next = '/app' }: { staff?: boolean; notice?: string; next?: string }) {
  return <div className="access-shell"><aside className="access-identity"><Brand /><p>Your calls. Your rules. Your private space.</p></aside><main id="main" tabIndex={-1} className="access-content"><p className="eyebrow">{staff ? 'Private operations' : 'Welcome to Redial'}</p><h1>{staff ? 'Staff sign-in' : 'Your quieter day starts here.'}</h1>{notices[notice] && <p role="status">{notices[notice]}</p>}<form action={authAction} className="review-form"><input type="hidden" name="next" value={next} /><input type="hidden" name="staff" value={staff ? '1' : '0'} /><label htmlFor="auth-email">Email</label><Input id="auth-email" name="email" type="email" autoComplete="email" required maxLength={254} /><label htmlFor="auth-password">Password</label><Input id="auth-password" name="password" type="password" autoComplete="current-password" minLength={12} maxLength={128} required /><div className="actions"><Button name="action" value="signin">Sign in</Button>{!staff && <Button name="action" value="signup" variant="outline">Create account</Button>}</div></form><details><summary>Forgot your password?</summary><form action={authAction} className="review-form"><label htmlFor="reset-email">Account email</label><Input id="reset-email" name="email" type="email" required /><Button name="action" value="reset">Send reset link</Button></form></details><p>{staff ? 'Operations requires an assigned staff role and an authenticator code.' : 'Confirm your email before creating a personal or business workspace.'}</p><Link href="/">Back to Redial</Link></main></div>;
}
