import Link from 'next/link';
import { notFound } from 'next/navigation';
import { liveControls } from '@/lib/live-controls';
import { Button } from '@/components/ui/button';
const details: Record<string, { heading: string; body: string }[]> = {
  insider: [{ heading: 'A quiet place in the conversation.', body: 'An authorized listener can follow a supported conversation while the caller and AI continue. Silence must be enforced by the voice provider, not a mute icon alone.' }, { heading: 'Leave without interrupting.', body: 'The listener is a separate participant. Leaving Insider must not end the caller’s conversation with the assistant.' }],
  gavel: [{ heading: 'When it is time to step in.', body: 'Your endpoint must be ready and muted before the handoff. AI audio input, output and tool execution stop, queued audio clears, and the AI participant is removed.' }, { heading: 'One clear owner of the call.', body: 'Only after the detach barrier is confirmed may the human be unmuted. A failed or canceled attempt retains a safe handler; the AI does not silently return after a completed takeover.' }],
  audible: [{ heading: 'A private word to your assistant.', body: 'Send bounded text guidance to the current AI session. It is separate from the caller transcript, expires quickly if undelivered, and becomes unavailable when the AI leaves.' }, { heading: 'Direction, with boundaries.', body: 'A delivery acknowledgment confirms delivery, not obedience. Guidance cannot grant tool access, change line permissions or bypass routing policy.' }],
  directory: [{ heading: 'The next person, thoughtfully connected.', body: 'Choose an approved destination and wait for explicit acceptance before the caller is transferred. A busy, unanswered or declined target leaves the previous handler in place.' }, { heading: 'Every route earns its readiness.', body: 'Saved numbers, custom numbers, users, extensions, SIP and ring groups have different prerequisites. Custom dialing needs action-bound confirmation; IVR routes need separate bounded DTMF validation.' }],
};
export default async function Feature({ params }: { params: Promise<{ name: string }> }) {
  const { name } = await params; const control = liveControls.find(item => item.name.toLowerCase() === name); if (!control) notFound();
  return <><header className="page-heading"><p className="eyebrow">Live Call Controls · {control.subtitle}</p><h1>{control.name}.<br /><em>Your call, considered.</em></h1><p>{control.description}</p></header><div className="info-grid">{details[name].map(item => <section className="info-card" key={item.heading}><h2>{item.heading}</h2><p>{item.body}</p></section>)}</div><section className="notice"><h2>Explore the local simulation.</h2><p>{control.requirement} The local simulator helps review the interaction; no real audio or provider action occurs.</p><div className="actions"><Button asChild><Link href="/demo/live">Try the control simulator</Link></Button><Button asChild variant="outline"><Link href="/how-it-works">How Redial works</Link></Button></div></section></>;
}
