import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { verifiedAccount } from '@/lib/supabase/server';
import { dashboardAction } from '@/lib/dashboard/actions';
import { authAction } from '@/lib/supabase/actions';
import { views, labels, capabilities, type Workspace, type Line, type DashboardRecord, type RecordKind } from '@/lib/dashboard/model';
import { RecordForm, Scope } from '@/components/dashboard/form';
import { DashboardNavigation } from '@/components/dashboard/navigation';
import { LaunchStatus } from '@/components/dashboard/launch-status';
import { CarrierSetup } from '@/components/dashboard/carrier-setup';
import type { SavedSetup } from '@/lib/dashboard/carrier-setup';
import { ContactImport } from '@/components/dashboard/contact-import';
import { appOrigin } from '@/lib/supabase/config';
import { contactReturnPath } from '@/lib/dashboard/contact-import';
import { Brand } from '@/components/brand';
import { ThemeToggle } from '@/components/theme-toggle';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { Card, Heading, Empty, Badge, Stat } from '@/components/review/ui';

export const dynamic='force-dynamic';
const kindFor: Record<string,RecordKind>={contacts:'contact',directory:'directory',callbacks:'callback',screening:'policy',agent:'agent',settings:'preferences',help:'ticket'};
const descriptions: Record<string,string>={contacts:'Save familiar voices and their call preferences.',directory:'Save destinations for review. A saved destination is not yet approved for dialing.',callbacks:'Keep a list of follow-ups. These are reminders, not scheduled calls.',screening:'Save the policy you want your line to use. Activation requires a verified connection.',agent:'Prepare an opening greeting and clear instructions for your assistant.',settings:'Save your preferences. Retention and delivery require the corresponding worker integration.',help:'Create a support request in the Redial operations inbox.'};
function NewWorkspace() { return <Card title="Create your workspace"><form action={dashboardAction} className="review-form"><label htmlFor="workspace-name">Workspace name</label><Input id="workspace-name" name="name" maxLength={100} required/><label htmlFor="workspace-type">Workspace type</label><Select id="workspace-type" name="type" defaultValue="personal" options={['personal','business']}/><Button name="action" value="workspace">Create workspace</Button></form></Card>; }

export default async function Dashboard({params,searchParams}:{params:Promise<{path?:string[]}>;searchParams:Promise<{workspace?:string;line?:string;notice?:string;page?:string;call?:string;import?:string}>}) {
  const query=await searchParams, path=(await params).path || [], view=path[0] || 'overview';
  const account=await verifiedAccount();
  if(!account) redirect(view==='contacts' && query.import==='phone' ? `/sign-in?next=${encodeURIComponent(contactReturnPath(`/app/contacts?${new URLSearchParams({workspace:query.workspace || '',line:query.line || ''})}`))}` : '/sign-in');
  const {db,user}=account;
  if(path.length>1 || !views.includes(view as typeof views[number])) notFound();
  const [workspaceResult,membershipResult]=await Promise.all([db.from('workspaces').select('id,name,type').order('created_at'),db.from('memberships').select('workspace_id,user_id,role,status').eq('user_id',user.id)]);
  if(workspaceResult.error || membershipResult.error) return <main id="main" className="access-content"><h1>Workspace data is unavailable</h1><p>Your account is signed in, but Redial could not load workspace permissions. Check the database migration and connection.</p><Link href="/app">Retry</Link></main>;
  const workspaces=workspaceResult.data as Workspace[], memberships=membershipResult.data;
  const workspace=workspaces.find(w=>w.id===query.workspace) || (!query.workspace?workspaces[0]:undefined);
  const member=memberships.find(m=>m.workspace_id===workspace?.id && m.status==='active');
  const lineResult=workspace && member ? await db.from('lines').select('id,name,owner_id,status').eq('workspace_id',workspace.id).order('created_at') : null;
  const lines=(lineResult?.data || []) as Line[];
  const line=lines.find(l=>l.id===query.line) || (!query.line?lines[0]:undefined);
  const w=workspace?.id || '', l=line?.id || '';
  const href=(next:string,extra='')=>`/app/${next}?workspace=${w}&line=${l}${extra}`;
  const kind=kindFor[view];
  const recordResult=workspace && member && kind && (line || kind==='ticket') ? await (kind==='ticket' ? db.from('workspace_records').select('*').eq('workspace_id',w).eq('kind',kind) : db.from('workspace_records').select('*').eq('workspace_id',w).eq('line_id',l).eq('kind',kind)).order('created_at',{ascending:false}).limit(100) : null;
  const records=(recordResult?.data || []) as DashboardRecord[];
  const page=Math.min(1000,Math.max(0,Number.parseInt(query.page || '0',10)||0));
  const callResult=line && ['overview','calls'].includes(view) ? await db.from('calls').select('id,caller,phone,outcome,summary,started_at,duration_seconds',{count:'exact'}).eq('workspace_id',w).eq('line_id',l).order('started_at',{ascending:false}).range(page*25,page*25+24) : null;
  const selectedCall=callResult?.data?.find(c=>c.id===query.call);
  const transcriptResult=selectedCall ? await db.from('transcript_segments').select('id,speaker,body').eq('workspace_id',w).eq('line_id',l).eq('call_id',selectedCall.id).order('sequence').limit(500) : null;
  const peopleResult=workspace && view==='people' ? await db.from('memberships').select('user_id,role,status').eq('workspace_id',w) : null;
  const grantsResult=line && view==='people' ? await db.from('line_access_grants').select('user_id,capability').eq('workspace_id',w).eq('line_id',l) : null;
  const subscriptionResult=workspace && view==='billing' ? await db.from('subscriptions').select('plan,status,current_period_end').eq('workspace_id',w).maybeSingle() : null;
  const connectionResult=workspace && view==='connections' ? await db.from('provider_connections').select('provider,status,checked_at').eq('workspace_id',w) : null;
  const auditResult=workspace && view==='audit' ? await db.from('audit_events').select('id,action,created_at').eq('workspace_id',w).order('created_at',{ascending:false}).limit(100) : null;
  const repliesResult=workspace && view==='help' ? await db.from('support_messages').select('id,ticket_id,body,created_at').eq('workspace_id',w).order('created_at').limit(500) : null;
  const setupResult=line && view==='numbers' ? await db.from('line_setup_drafts').select('body,version,updated_at').eq('workspace_id',w).eq('line_id',l).maybeSingle() : null;
  const setupAccess=line && view==='numbers' ? await db.rpc('can_manage_line_setup',{w,l}) : null;
  const error=[setupResult,setupAccess,repliesResult,lineResult,recordResult,callResult,transcriptResult,peopleResult,grantsResult,subscriptionResult,connectionResult,auditResult].some(result=>result?.error);
  return <div className="review-shell"><aside className="review-sidebar"><Brand/><DashboardNavigation workspace={w} line={l} view={view}/><div className="sidebar-profile"><p>{user.email}</p><Link href="/account">Account settings</Link></div></aside><div className="review-body"><header className="review-topbar"><strong>{workspace?.name || 'Your workspace'}</strong><div className="actions"><ThemeToggle/><form action={authAction}><Button variant="outline" name="action" value="signout">Sign out</Button></form></div></header><main id="main" tabIndex={-1} className="review-content">
    <details className="workspace-card"><summary>Workspace & line</summary><div className="actions">{workspaces.map(item=><Link key={item.id} href={`/app?workspace=${item.id}`} className="action-link">{item.name} · {item.type}</Link>)}</div><div className="actions">{lines.map(item=><Link key={item.id} href={`/app/${view}?workspace=${w}&line=${item.id}`} className="action-link">{item.name}</Link>)}</div>{workspace && <NewWorkspace/>}</details>
    {query.notice && <p role="status" className={query.notice==='failed'?'error-message':'success-message'}>{query.notice==='failed'?'The change could not be saved. Check your input and access, then reload before retrying.':query.notice==='invited'?'If that person has a verified Redial account, an invitation is waiting in their workspace. No email was sent.':query.notice==='origin'?'Use the configured Redial domain to save changes.':'Saved.'}</p>}
    {error && <p role="alert" className="error-message">Some workspace data could not be loaded. Reload to retry; no demo data has been substituted.</p>}
    {memberships.filter(m=>m.status==='invited').map(m=><Card key={m.workspace_id} title="Workspace invitation"><p>You have been invited as {m.role}.</p><form action={dashboardAction}><Scope workspace={m.workspace_id} view="overview"/><Button name="action" value="accept">Accept invitation</Button></form></Card>)}
    {!workspace || !member ? <><Heading title="A space for your calls." description="Create a personal or business workspace, or accept an invitation."/><NewWorkspace/></> : <>
    <Heading eyebrow={`${workspace.type} workspace${line?` · ${line.name}`:''}`} title={labels[views.indexOf(view as typeof views[number])]} description={descriptions[view] || 'Your workspace, with access scoped to your account and line.'}/>
    {view==='contacts' && line && <ContactImport key={`${w}:${l}`} workspace={w} line={l} lineName={`${workspace.name} · ${line.name}`} existingPhones={records.map(record=>String(record.body.phone || ''))} phoneUrl={`${appOrigin()}/app/contacts?${new URLSearchParams({workspace:w,line:l,import:'phone'})}`} autoOpen={query.import==='phone'}/>}
    {!line && !['help','people','billing','connections','audit','numbers'].includes(view) ? <Empty title="Choose a line you can access">Create a line in Numbers & setup, or ask its owner for the appropriate permission.</Empty> : <>
    {view==='overview' && <><div className="stat-grid"><Stat label="Accessible calls" value={callResult?.count || 0} detail="On this line"/><Stat label="Line status" value={line?.status || 'No line'} detail="Provider verification required"/><Stat label="Workspace" value={workspace.type} detail="Content permissions remain separate from billing"/></div><Card title="Finish connecting your line"><p>Your settings and records are stored in Supabase. Calls will appear after a verified voice integration delivers them.</p><Link href={href('numbers')} className="action-link">Review number setup</Link></Card></>}
    {['overview','calls'].includes(view) && <Card title="Call inbox">{callResult?.data?.length ? callResult.data.map(call=><article className="record-row" key={call.id}><div className="grow"><Link href={href('calls',`&page=${page}&call=${call.id}`)}><strong>{call.caller}</strong></Link><p>{call.phone} · {new Date(call.started_at).toLocaleString('en-US',{timeZone:'UTC'})} UTC</p><p>{call.summary}</p></div><Badge>{call.outcome}</Badge></article>) : <Empty title="Your inbox is clear">No accessible calls have been received on this line.</Empty>}<div className="actions">{page>0 && <Link href={href('calls',`&page=${page-1}`)}>Previous</Link>}{(callResult?.count || 0)>(page+1)*25 && <Link href={href('calls',`&page=${page+1}`)}>Next</Link>}</div>{selectedCall && <section><h2>The conversation</h2>{transcriptResult?.data?.length ? transcriptResult.data.map(segment=><p key={segment.id}><strong>{segment.speaker}</strong> {segment.body}</p>) : <p>No retained transcript is available with your permissions.</p>}</section>}</Card>}
    {kind && <><Card title={['policy','agent','preferences'].includes(kind)?'Your saved draft':`Add ${kind==='ticket'?'support request':kind}`}><RecordForm kind={kind} record={['policy','agent','preferences'].includes(kind)?records[0]:undefined} workspace={w} line={l} view={view}/></Card>{!['policy','agent','preferences'].includes(kind) && <Card title="Saved records" subtitle="Showing up to 100 most recent records">{records.map(record=><details className="workspace-card" key={record.id}><summary>{String(record.body.name || record.body.subject)}{kind==='callback' && record.body.done?' · Completed':''}</summary><RecordForm kind={kind} record={record} workspace={w} line={l} view={view}/>{kind==='ticket' && repliesResult?.data?.filter(reply=>reply.ticket_id===record.id).map(reply=><p key={reply.id}><strong>Staff reply:</strong> {reply.body}</p>)}</details>)}{!records.length && <p>No records yet.</p>}</Card>}</>}
    {view==='numbers' && <>{line && <Card title="Set up incoming calls"><p>Choose your provider and connection method. Saved choices remain a draft until routing and fallback are verified.</p>{setupAccess?.data===true ? <CarrierSetup key={`${w}:${l}`} workspace={w} line={l} saved={setupResult?.data as SavedSetup | undefined} unavailable={Boolean(setupResult?.error)}/> : <p>Ask the line owner for permission to manage this line?s setup.</p>}</Card>}<Card title="Your accessible lines">{lines.map(item=><article key={item.id} className="record-row"><strong>{item.name}</strong><Badge>{item.status}</Badge></article>)}</Card><Card title="Add a line"><p>This creates a workspace line, not a phone number purchase or forwarding change.</p><form action={dashboardAction} className="review-form"><Scope workspace={w} line={l} view={view}/><label htmlFor="line-name">Line name</label><Input id="line-name" name="name" required maxLength={100}/><Button name="action" value="line">Create line</Button></form></Card></>}
    {view==='connections' && <><LaunchStatus/><Card title="Connection status">{['Supabase','Twilio','xAI','Square','Resend'].map(provider=><article className="record-row" key={provider}><strong>{provider}</strong><Badge>{provider==='Supabase'?'Account and database connected':connectionResult?.data?.find(c=>c.provider.toLowerCase()===provider.toLowerCase())?.status || 'Not configured'}</Badge></article>)}<p>Credentials alone do not establish call routing, checkout, or delivery. Each integration needs its own verification.</p></Card></>}
    {view==='live' && <div className="workspace-grid equal">{[['Insider','Silent listening requires provider-enforced mute and line permission.'],['Gavel','Human takeover requires verified AI detachment.'],['Audible','Private guidance requires an active assistant session.'],['Directory','Transfers require approved destinations and provider acceptance.']].map(([title,body])=><Card key={title} title={title}><p>{body}</p><Badge>Unavailable · voice gateway not connected</Badge></Card>)}</div>}
    {view==='billing' && <Card title="Membership">{subscriptionResult?.data ? <><h2>{subscriptionResult.data.plan}</h2><Badge>{subscriptionResult.data.status}</Badge><p>{subscriptionResult.data.current_period_end?`Period ends ${subscriptionResult.data.current_period_end}`:''}</p></> : <p>No subscription is available with your billing permissions. Checkout requires a verified Square integration.</p>}</Card>}
    {view==='people' && <><Card title="Workspace members">{peopleResult?.data?.map(person=><article className="record-row" key={person.user_id}><div className="grow"><strong>{person.user_id===user.id?'You':person.user_id}</strong><p>{person.role} · {person.status}</p></div>{['owner','admin'].includes(member.role) && ['member','billing'].includes(person.role) && person.status!=='revoked' && <form action={dashboardAction}><Scope workspace={w} line={l} view={view}/><input type="hidden" name="user" value={person.user_id}/><Button variant="outline" name="action" value="revoke">Revoke membership</Button></form>}</article>)}</Card>{['owner','admin'].includes(member.role) && <Card title="Invite an existing account"><p>Ask the person to create and verify their Redial account first. They can then accept this invitation from their dashboard. Billing membership grants no call content.</p><form action={dashboardAction} className="review-form"><Scope workspace={w} line={l} view={view}/><label htmlFor="invite-email">Email</label><Input id="invite-email" name="email" type="email" required/><label htmlFor="invite-role">Role</label><Select id="invite-role" name="role" defaultValue="member" options={['member','billing']}/><Button name="action" value="invite">Create invitation</Button></form></Card>}{line?.owner_id===user.id && <Card title="Line permissions"><p>Only the line owner can grant access. Live permissions do not activate provider capabilities.</p>{peopleResult?.data?.filter(p=>p.user_id!==user.id && p.status==='active').map(person=><details key={person.user_id}><summary>{person.user_id}</summary>{capabilities.map(c=>{const enabled=grantsResult?.data?.some(g=>g.user_id===person.user_id && g.capability===c);return <form action={dashboardAction} className="record-row" key={c}><Scope workspace={w} line={l} view={view}/><input type="hidden" name="user" value={person.user_id}/><input type="hidden" name="capability" value={c}/><input type="hidden" name="enabled" value={String(!enabled)}/><span className="grow">{c.replaceAll('_',' ')}</span><Button name="action" value="grant" variant="outline">{enabled?'Revoke':'Grant'}</Button></form>;})}</details>)}</Card>}</>}
    {view==='audit' && <Card title="Workspace activity">{auditResult?.data?.length ? auditResult.data.map(event=><article className="record-row" key={event.id}><strong>{event.action}</strong><span>{event.created_at}</span></article>) : <p>No activity is available with your permissions.</p>}</Card>}
    </>}
    </>}
  </main></div></div>;
}
